# Generated by Django 3.2.5 on 2021-07-10 20:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre Productor')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('bio', tinymce.models.HTMLField()),
                ('image', models.URLField(blank=True, max_length=255)),
                ('facebook_link', models.URLField(blank=True, max_length=255)),
                ('twitter_link', models.URLField(blank=True, max_length=255)),
                ('instagram_link', models.URLField(blank=True, max_length=255)),
                ('youtube_link', models.URLField(blank=True, max_length=255)),
                ('web_link', models.URLField(blank=True, max_length=255)),
                ('state', models.BooleanField(default=True, verbose_name='Activar/Desactivar Productor')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo Categoria')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title')),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo Lanzamiento')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title')),
                ('image', models.URLField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('iframe', models.TextField()),
                ('published', models.BooleanField(default=True, verbose_name='Publicar')),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='label.artist', verbose_name='Artista')),
                ('category', models.ManyToManyField(to='label.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Lanzamiento',
            },
        ),
    ]
